Tried adding sphere definition into ray code
vyuham/rtrcrs pull request #1
Opened 2021-04-25 06:27 UTC by firebreath1001

I'm currently working on the code to complete implementation of "Ray Tracing In One Weekend".
- performed cargo format.
- wrote code for sphere if ray intersects.

TODO: FIX necessary, improper image being generated.

2021-04-25 08:48 UTC, de-sh commented
We are supposed to be getting the image below when using the parameters mentioned in the tutorial:
![desired sphere shaped output](https://raytracing.github.io/images/img-1.03-red-sphere.png)
But we end up receiving this:
![output](https://user-images.githubusercontent.com/18750864/115987053-17254b00-a5d1-11eb-8c21-7866251e314f.png)


We need to look at the code for `Ray` and `Vec3` to figure out why that is.

2021-04-26 17:59 UTC, de-sh requested changes

2021-04-26 17:59 UTC, de-sh commented on src/ray.rs
> +            oc.dot(self.dir) - radius * radius,
I think you meant
```
oc.dot(oc)
```

2021-04-26 17:59 UTC, de-sh commented on src/ray.rs
> +        if self.hit_sphere(Point3::new(0.0, 0.0, 2.0), 0.01) {
We should be getting the correct output as shown in the tutorial. This should be
```
if self.hit_sphere(Point3(0.0, 0.0, -1.0), 0.5) { ... }
```

2021-05-08 18:01 UTC, de-sh commented on src/ray.rs
> +            oc.dot(self.dir) - radius * radius,
This is the cause of all out problems 🤦🏼

2021-05-08 18:18 UTC, merged

2021-05-08 19:09 UTC, firebreath1001 commented on src/ray.rs
> +            oc.dot(self.dir) - radius * radius,
oh :D thanks a lot man!! will patch it up!

2021-05-08 20:32 UTC, de-sh commented on src/ray.rs
> +            oc.dot(self.dir) - radius * radius,
I patched it up in 161097e, please try implementing more of the code.